"""add password_hash to parent

Revision ID: 037e599f4bd3
Revises: be9141d876cd
Create Date: 2026-08-18 22:09:24.577738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037e599f4bd3'
down_revision = 'be9141d876cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
