"""create_domain_models

Revision ID: be9141d876cd
Revises: 
Create Date: 2026-08-09 21:58:59.819777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9141d876cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lsa_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lsa_profiles_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_lsa_profiles_is_active'), ['is_active'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_email'), ['email'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('lsa_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_start_before_end'),
    sa.ForeignKeyConstraint(['lsa_id'], ['lsa_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.create_index('idx_bookings_lsa_overlap', ['lsa_id', 'status', 'start_time', 'end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_lsa_id'), ['lsa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_requests_parent_id'), ['parent_id'], unique=False)

    op.create_table('lsa_skills',
    sa.Column('lsa_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lsa_id'], ['lsa_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lsa_id', 'skill_id')
    )
    with op.batch_alter_table('lsa_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lsa_skills_lsa_id'), ['lsa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lsa_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('external_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_booking_id'), ['booking_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_external_payment_id'), ['external_payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_external_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_booking_id'))

    op.drop_table('payments')
    with op.batch_alter_table('lsa_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lsa_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_lsa_skills_lsa_id'))

    op.drop_table('lsa_skills')
    with op.batch_alter_table('booking_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_requests_parent_id'))
        batch_op.drop_index(batch_op.f('ix_booking_requests_lsa_id'))
        batch_op.drop_index('idx_bookings_lsa_overlap')

    op.drop_table('booking_requests')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))

    op.drop_table('skills')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_email'))

    op.drop_table('parents')
    with op.batch_alter_table('lsa_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_is_active'))
        batch_op.drop_index(batch_op.f('ix_lsa_profiles_email'))

    op.drop_table('lsa_profiles')
    # ### end Alembic commands ###
